# Development image: runs the Go service with Air hot reload.
FROM golang:1.25

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/air-verse/air@latest

ENV PATH=/go/bin:$PATH \
    GOMODCACHE=/go-mod-cache \
    GOCACHE=/go-cache

CMD ["air", "-c", ".air.toml"]
