services:
  # Приложение на Go
  app:
    # Собираем образ из Dockerfile.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Монтируем текущую директорию внутрь контейнера
    volumes:
      - .:/app
    # Пробрасываем порт API наружу
    ports:
      - "8080:8080"
    # Переменные окружения для подключения к БД и Redis
    env_file:
      - path: .env.example
      - path: .env
        required: false
    # Сначала должны запуститься db и redis
    depends_on:
      - db
      - redis

  # База данных PostgreSQL
  db:
    # Официальный образ Postgres версии 15
    image: postgres:15
    # Если контейнер упадёт, он перезапустится
    restart: always
    # Настройки базы (логин, пароль, имя базы)
    env_file:
      - path: .env.example
      - path: .env
        required: false
    # Пробрасываем порт БД наружу
    ports:
      - "5432:5432"
    # Данные БД сохраняем в отдельный том (не пропадут при перезапуске)
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis
  redis:
    # Официальный образ Redis версии 7
    image: redis:7
    # Перезапуск при сбое
    restart: always
    # Проброс порта наружу
    ports:
      - "6379:6379"
    env_file:
      - path: .env.example
      - path: .env
        required: false
    # (опционально) примонтировать том для сохранения дампов
    # volumes:
    #   - redis_data:/data

# Определяем тома для хранения данных
volumes:
  db_data:
  # redis_data:
